name: Build Notepad++ Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build DLL
      run: |
        mkdir build
        cd build
        echo Building plugin...

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BaswareUtilityTools
        path: .
